import "./globals.css";

export const metadata = {
  title: "Acme",
  description: "Generated by create next app",
};

export default function RootLasyout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="sm: scroll-smooth">
      <body
        className={"min-h-screen bg-slate-50 dark:bg-black dark:text-white"}
      >
        {children}
      </body>
    </html>
  );
}
